### ISSUE TITLE
Packet Tracer 7.1

### ISSUE THREAD

**Issue by Apfelmus1337** [alexbakker/ptpwn#2]
Could you please update the tool to Packet Tracer Version 7.1?

**Comment by alexbakker** [comment]
I will probably not resume work on this project any time soon. Sorry.

I'd merge a pull requests that adds support for it though.

**Comment by akss1** [comment]
> static PacketTracer[] _versions =
        {
            new PacketTracer(new IntPtr(**0x0281F628**), new IntPtr(**0x00C78633**), new IntPtr(**0x00C78880**), "6.2.0.0052"),
            new PacketTracer(new IntPtr(**0x02D97670**), new IntPtr(**0x00C823C3**), new IntPtr(**0x00C82610**), "6.3.0.0009"),
            new PacketTracer(new IntPtr(**0x02B2984C**), new IntPtr(**0x00CFC423**), new IntPtr(**0x00CFC6A9**), "7.0.0.0201"),
        };
> 
Hello my friend. How did you find out the addresses for VersionsPart, TargetPtr and EndpointPtr? @alexbakker

**Comment by alexbakker** [comment]
Support for 7.1 was added in 567e3bee7cd347a0c1b7125016ebd5a8ec57e239.
