### ISSUE TITLE
Open ptpwn

### ISSUE THREAD

**Issue by ghostknives** [alexbakker/ptpwn#3]
Hi,

How do i run ptpwn? Do I have to load the file into cisco or do I have to put in cisco files? or do I have to start it with another program?

Ghostknives

**Comment by alexbakker** [comment]
You need to compile it with Visual Studio and start the resulting executable.

**Comment by ghostknives** [comment]
![image](https://user-images.githubusercontent.com/39366963/40173343-c7bd9142-59d1-11e8-9f54-e255a3a69fc8.png)

thanks for your quick reply. I have been able to start the program via microsoft visual. Because I use version 7.1 I understand that I must replace the code with:
static PacketTracer[] _versions =
{
new PacketTracer(new IntPtr(0x0281F628), new IntPtr(0x00C78633), new IntPtr(0x00C78880), "6.2.0.0052"),
new PacketTracer(new IntPtr(0x02D97670), new IntPtr(0x00C823C3), new IntPtr(0x00C82610), "6.3.0.0009"),
new PacketTracer(new IntPtr(0x02B2984C), new IntPtr(0x00CFC423), new IntPtr(0x00CFC6A9), "7.0.0.0201"),
};


I now only get an error message. Do you happen to know how I can solve this?

Ghostknives

**Comment by alexbakker** [comment]
Version 7.1 is not supported. See also: https://github.com/alexbakker/ptpwn/issues/2.

I have some spare time later today. I'll check if I still have access to packet tracer binaries and see if I can update ptpwn to support the latest version.

**Comment by ghostknives** [comment]
Thank you very much. The whole class 1b ict service management would be very happy with it. If you no longer have access you would be able to email me then I give you temporary access to my account if you send me an email then I give you the data. (germenschuurman@gmail.com)

**Comment by alexbakker** [comment]
@ghostknives Support for 7.1 was added in 567e3bee7cd347a0c1b7125016ebd5a8ec57e239. Please let me know if it works for you.

**Comment by ghostknives** [comment]
@alexbakker It works great thanks! Class 1B thanks you too!

**Comment by alexbakker** [comment]
Great! You're welcome.
